
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SUBMODULE_STRATEGY: recursive

# for older versions of Gitlab runner
#before_script:
#  - git submodule sync --recursive
#  - git submodule update --init --recursive

before_script:
  - ls -al

cache:
  paths:
    - .m2/repository/
    - "*/target"

stages:
  - build
  - test
  - push

Build:
  image: maven:latest
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

Test:
  image: maven:latest
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

Package-And-Push:
  image: herychemo/dind-java-maven:latest
  stage: push
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY <<< "$CI_REGISTRY_PASSWORD"
    - mvn $MAVEN_CLI_OPTS package deploy -DskipTests
    - docker rmi $(docker images -qa -f 'dangling=true')

