image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SUBMODULE_STRATEGY: recursive

# for older versions of Gitlab runner
#before_script:
#  - git submodule sync --recursive
#  - git submodule update --init --recursive

before_script:
  - ls -al

cache:
  paths:
    - .m2/repository/
    - "*/target"

stages:
  - build
  - test

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

Test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
