version: "3.3"

services:

  RabbitMQ-Server:
    image: rabbitmq:3.7-rc-management-alpine
    container_name: RabbitMQ-Server
    hostname: RabbitMQ-Server
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1

  elasticsearchserver:
    image: elasticsearch:6.6.1
    container_name: elasticsearchserver
    hostname: elasticsearchserver
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  kibanaserver:
    image: kibana:6.6.1
    container_name: kibanaserver
    hostname: kibanaserver
    environment:
      - ELASTICSEARCH_URL=http://tasks.elasticsearchserver:9200
      - ELASTICSEARCH_HOSTS=http://tasks.elasticsearchserver:9200
    ports:
      - 5601:5601
    volumes:
      - ${PWD}/DockerServices/conf/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearchserver
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logstashserver:
    image: logstash:6.6.1
    container_name: logstashserver
    hostname: logstashserver
    environment:
      - RABBIT_MQ_HOST=tasks.RabbitMQ-Server
      - ELASTICSEARCH_HOST=tasks.elasticsearchserver
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/DockerServices/conf/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - logstash-pipeline:/usr/share/logstash/pipeline
    depends_on:
      - RabbitMQ-Server
      - elasticsearchserver
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  ZipkinServer:
    image: openzipkin/zipkin
    container_name: ZipkinServer
    hostname: ZipkinServer
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=tasks.elasticsearchserver
      - ES_HTTP_LOGGING=BODY
    ports:
      - 9411:9411
    depends_on:
      - elasticsearchserver
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  PostgresDatabase:
    image: postgres:11.2
    container_name: PostgresDatabase
    hostname: PostgresDatabase
    environment:
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_USER=dbo_admin
      - POSTGRES_DB=cloud_db
    ports:
      - 5432:5432
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker


  ConfigServer:
    build:
      context: ./ConfigServer/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=ConfigServer.jar
    image: grayraccoon/sample-cloud-config-server:0.0.1-SNAPSHOT
    container_name: ConfigServer
    hostname: ConfigServer
    ports:
      - 8888:8888
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1

  EurekaServer:
    build:
      context: ./EurekaServer/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=EurekaServer.jar
    image: grayraccoon/sample-cloud-eureka-server:0.0.1-SNAPSHOT
    container_name: EurekaServer
    hostname: EurekaServer
    environment:
      - SPRING_PROFILES_ACTIVE=swarm
    ports:
      - 8761:8761
    depends_on:
      - ConfigServer
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  auth-ms:
    build:
      context: ./AuthMs/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=auth-ms.jar
    image: grayraccoon/sample-cloud-auth-ms:0.0.1-SNAPSHOT
    container_name: Auth-Ms
    hostname: Auth-Ms
    environment:
      - SPRING_PROFILES_ACTIVE=swarm
    ports:
      - 9869:9869
    depends_on:
      - ConfigServer
      - EurekaServer
      - ZipkinServer
      - logstashserver
      - RabbitMQ-Server
      - PostgresDatabase
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 2

  ZuulApiProxy:
    build:
      context: ./ZuulApiProxy/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=ZuulApiProxy.jar
    image: grayraccoon/sample-cloud-zuul-api-proxy:0.0.1-SNAPSHOT
    container_name: ZuulApiProxy
    hostname: ZuulApiProxy
    environment:
      - SPRING_PROFILES_ACTIVE=swarm
    ports:
      - 8081:8081
    depends_on:
      - ConfigServer
      - EurekaServer
      - ZipkinServer
      - logstashserver
      - RabbitMQ-Server
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1

  turbine-server:
    build:
      context: ./turbine-server/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=turbine-server.jar
    image: grayraccoon/sample-cloud-turbine-server:0.0.1-SNAPSHOT
    container_name: turbine-server
    hostname: turbine-server
    environment:
      - SPRING_PROFILES_ACTIVE=swarm
    ports:
      - 9003:9003
    depends_on:
      - ConfigServer
      - EurekaServer
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1

  accounts-ms:
    build:
      context: ./AccountsMs/
      dockerfile: Dockerfile
      args:
        - JAR_FILE=accounts-ms.jar
    image: grayraccoon/sample-cloud-accounts-ms:0.0.1-SNAPSHOT
    container_name: Accounts-Ms
    hostname: Accounts-Ms
    environment:
      - SPRING_PROFILES_ACTIVE=swarm
    ports:
      - 9871:9871
    depends_on:
      - ConfigServer
      - EurekaServer
      - ZipkinServer
      - logstashserver
      - RabbitMQ-Server
      - PostgresDatabase
    networks:
      - SpringCloudNetwork
    deploy:
      replicas: 1





  dashboard:
    image: charypar/swarm-dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8082:8082
    environment:
      PORT: 8082
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  logstash-pipeline:
    driver_opts:
      type: none
      device: ${PWD}/DockerServices/conf/logstash/pipeline
      o: bind

networks:
  SpringCloudNetwork:


# Quick reference commands:
# docker stack deploy -c docker-compose.yml cloud
# clear && docker stack services cloud && echo && docker stack ps cloud && echo && docker ps -a
