
server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URL:https://github.com/herychemo/SampleConfigRepo.git}
          #username: ${config_server_username}
          #password: ${config_server_password}
          skip-ssl-validation: true
          timeout: 6

