
server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URL:https://gitlab.com/herychemo/SampleConfigRepo.git}
          #username: ${config_server_username}
          #password: ${config_server_password}
          skip-ssl-validation: true
          timeout: 8

logging:
  file: ${java.io.tmpdir}/logs/${spring.application.name}.log